version: '3'

services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    ports:
      - 8080:8080
      - 35729:35729 # port for livereload
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload --watch --incremental
